version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
  pre_build:
    commands:
      - echo "Current directory:"
      - pwd
      - echo "Listing repository contents:"
      - ls -la
      - echo "Changing to frontend directory..."
      - cd frontend && pwd
      - echo "Listing frontend directory contents:"
      - ls -la
      - echo "Installing dependencies..."
      - cd frontend && npm install
  build:
    commands:
      - echo "Building React app..."
      - cd frontend && npm run build
      - echo "Listing build directory contents..."
      - cd frontend && ls -la build/
  post_build:
    commands:
      - echo "Build completed successfully"

artifacts:
  files:
    - '**/*'
  base-directory: frontend/build