version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - cd frontend
      - npm install
  build:
    commands:
      - echo Building app...
      - npm run build
  post_build:
    commands:
      - echo Uploading to real S3 bucket...
      - aws s3 sync build/ s3://qairline-frontend/ --delete
