version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
  pre_build:
    commands:
      - echo "Repository structure:"
      - find . -name "package.json" -type f
      - echo "Installing frontend dependencies..."
      - npm install --prefix frontend
  build:
    commands:
      - echo "Building React app..."
      - npm run build --prefix frontend
      - echo "Checking build output..."
      - ls -la frontend/build/
  post_build:
    commands:
      - echo "Build completed successfully"

artifacts:
  files:
    - '**/*'
  base-directory: frontend/build