version: 0.2

phases:
  pre_build:
    commands:
      - echo "Node.js version:"
      - node --version
  build:
    commands:
      - npm install
      - npm run build
  post_build:
    commands:
      - echo "Build completed"
artifacts:
  files:
    - '**/*'
  base-directory: build
