services:
  backend:
    image: tenebris2/qairline-repo:backend
    build:
      context: ./backend
    environment:
      - DATABASE_URL=postgresql://postgres:mysecretpassword@db:5432/airline_db
      - MAIL_USERNAME=${{ secrets.MAIL_USERNAME }}
      - MAIL_PASSWORD=${{ secrets.MAIL_PASSWORD }}
      - MAIL_SERVER=${{ secrets.MAIL_SERVER }}
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: 
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
